Repository trade-market/trade-market-FE, pull requests merged in 2023-10, with the labels that each got.

#57 [알림 페이지] 키워드 설정 페이지 화면 구현
  src/Assets/Icons/X_button.svg
  src/Pages/Notifications/Notifications.tsx
  src/Pages/SetNotificationKeywords/SetNotificationKeywords.tsx
  src/Pages/SetNotificationKeywords/index.tsx
  src/Router.tsx
  src/components/MyPage/Profile.tsx
  src/components/SetNotificationKeywords/InputContainer.tsx
  src/components/SetNotificationKeywords/KeywordItem.tsx
  src/components/SetNotificationKeywords/KeywordList.tsx
  src/components/SetNotificationKeywords/KeywordsContainer.tsx
  src/components/SetNotificationKeywords/TitleContainer.tsx
  src/components/common/CommonHeader/CommonHeader.tsx
Labels: Feature

#63 [가입 페이지] 가입 축하 모달 화면 구현 및 404
  src/Pages/NotFound/NotFound.tsx
  src/Pages/NotFound/index.tsx
  src/Pages/SingUp/SignUp.tsx
  src/Router.tsx
  src/components/Signup/SignUpSuccessModal.tsx
  src/components/common/CommonModal.tsx
  src/main.tsx
  src/styles/GlobalStyles.ts
Labels: Feature

#65 [채팅페이지] 채팅 기능 수정
  src/Pages/Chat/ChatList/index.tsx
  src/Pages/Chat/ChatRoom/index.tsx
  src/components/Chat/ChatRoom/ChatInput/index.tsx
  src/components/Chat/ChatRoom/Chatting/Chatting.tsx
  src/components/Chat/ChatRoom/InfoCollapse/index.tsx
Labels: Enhancement

#69 [회원 인증] RTK Query 마이그레이션 및 API 명세서 타입 적용
  src/App.tsx
  src/Pages/MyPage/EditProfile/EditProfile.tsx
  src/Pages/MyPage/MyPage.tsx
  src/Pages/SingUp/SignUp.tsx
  src/Router.tsx
  src/api/client.ts
  src/components/Auth/OAuthRedirectHandler.tsx
  src/components/Auth/Spinner.tsx
  src/components/MyPage/Profile.tsx
  src/components/PrivateRoute.tsx
  src/components/PublicRoute.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/ProfileSetupForm/ProfileSetupForm.tsx
  src/hooks/useAuth.ts
  src/hooks/useUser.ts
  src/mocks/handlers.ts
  src/service/AuthService.ts
  src/service/TokenService.ts
  src/service/UserService.ts
  src/store/api/apiSlice.ts
  src/store/api/authApiSlice.ts
  src/store/api/userApiSlice.ts
  src/store/slices/userSlice.ts
  src/store/store.ts
  src/types/AuthTypes.ts
  src/types/UserTypes.ts
  src/utils/ScrollToTop.tsx
  src/utils/tokenStorage.ts
Labels: Enhancement, Feature
