Repository trade-market/trade-market-FE, pull requests merged in 2023-08, with the labels that each got.

#9 로그인 & 회원 가입 페이지 화면 구현
  src/App.tsx
  src/Assets/Icons/HomeScreen/1_1.svg
  src/Assets/Icons/HomeScreen/Chat_Disable.svg
  src/Assets/Icons/HomeScreen/Home_Disable.svg
  src/Assets/Icons/HomeScreen/MY_Black.svg
  src/Assets/Icons/HomeScreen/MY_Disable.svg
  src/Assets/Icons/HomeScreen/MY_활성화.svg
  src/Assets/Icons/HomeScreen/Search.svg
  src/Assets/Icons/HomeScreen/교환.svg
  src/Assets/Icons/HomeScreen/글쓰기.svg
  src/Assets/Icons/HomeScreen/오퍼.svg
  src/Assets/Icons/HomeScreen/좋아요 O.svg
  src/Assets/Icons/HomeScreen/좋아요 X.svg
  src/Assets/Icons/HomeScreen/채팅_활성화.svg
  src/Assets/Icons/HomeScreen/홈_활성화.svg
  src/Assets/Images/google.png
  src/Assets/Images/kakao.png
  src/Assets/Images/naver.png
  src/Pages/Auth/Auth.tsx
  src/Pages/Auth/AuthStyles.ts
  src/components/common/Auth/SocialButton.tsx
  src/components/common/Auth/SocialButtonStyles.ts
  src/components/common/Header/HeaderStyles.ts
  src/components/common/Layout/LayoutStyles.ts
  src/components/common/NavigationBar/NavigationBar.tsx
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: feature

#14 우리동네 게시글 화면 구현 완료
  .DS_Store
  src/Assets/Icons/Home/Post/Icon_1vs1.svg
  src/Assets/Icons/Home/Post/Icon_exchang.svg
  src/Assets/Icons/Home/Post/Icon_like.svg
  src/Assets/Icons/Home/Post/Icon_offer.svg
  src/Assets/Icons/Home/Post/Icon_unlike.svg
  src/Assets/Icons/Home/Post/Img_post.png
  src/Pages/Home/Exchange/ExchangeMenu/ExchageMenuStyles.ts
  src/Pages/Home/Home.tsx
  src/Pages/Home/HomeStyles.ts
  src/Pages/Home/OurTownPost/DumyData.tsx
  src/Pages/Home/OurTownPost/OurTownPost.tsx
  src/Pages/Home/OurTownPost/OurTownPostStyles.ts
  src/Pages/Home/OurTownPost/PostComponents/ContentSection.tsx
  src/Pages/Home/OurTownPost/PostComponents/ImgSection.tsx
  src/Pages/Home/OurTownPost/PostComponents/PostComponent.tsx
  src/Pages/Home/OurTownPost/PostComponents/SebSection.tsx
Labels: feature

#19 프로젝트 상대 경로 -> 절대 경로로 변경
  .eslintrc
  package-lock.json
  package.json
  src/Pages/Auth/Auth.tsx
  src/Pages/Home/Exchange/ExchangeMenu/ExchageIcons.ts
  src/Pages/Home/OurTownPost/PostComponents/ContentSection.tsx
  src/Pages/Home/OurTownPost/PostComponents/ImgSection.tsx
  src/Pages/Home/OurTownPost/PostComponents/SebSection.tsx
  src/Pages/Home/Swiper/SwiperBanner.tsx
  src/Pages/Home/WriteButton/WriteButton.tsx
  src/Pages/Home/WriteButton/WriteButtonStyles.ts
  src/components/ProfileSetup/NicknameSetting.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/NavigationBar/NaviMenu/NaviChat.tsx
  src/components/common/NavigationBar/NaviMenu/NaviHome.tsx
  src/components/common/NavigationBar/NaviMenu/NaviMy.tsx
  tsconfig.json
  vite.config.ts
Labels: enhancement

#21 뒤로가기 버튼 기능 구현
  .DS_Store
  src/Assets/Icons/Home/Goback.svg
  src/Pages/Home/Home.tsx
  src/Pages/ProfileSetup/ProfileSetup.tsx
  src/components/Home/Exchange/ExchangeMenu/ExchageIcons.ts
  src/components/Home/Exchange/ExchangeMenu/ExchageMenuStyles.ts
  src/components/Home/Exchange/ExchangeMenu/ExchangeMenu.tsx
  src/components/Home/Exchange/ExchangeMenu/MapIcons.tsx
  src/components/Home/OurTownPost/DumyData.tsx
  src/components/Home/OurTownPost/OurTownPost.tsx
  src/components/Home/OurTownPost/OurTownPostStyles.ts
  src/components/Home/OurTownPost/PostComponents/ContentSection.tsx
  src/components/Home/OurTownPost/PostComponents/ImgSection.tsx
  src/components/Home/OurTownPost/PostComponents/PostComponent.tsx
  src/components/Home/OurTownPost/PostComponents/SebSection.tsx
  src/components/Home/Swiper/SwiperBanner.tsx
  src/components/Home/Swiper/SwiperBannerStyles.ts
  src/components/Home/WriteButton/WriteButton.tsx
  src/components/Home/WriteButton/WriteButtonStyles.ts
  src/components/common/CommonHeader/CommonHeader.tsx
  src/components/common/CommonHeader/CommonHeaderStyles.ts
  src/components/common/CommonHeader/GobackBtn.tsx
  src/components/common/Header/HeaderStyles.ts
Labels: feature

#23 위치 설정 페이지 화면 구현
  .gitignore
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/Assets/Icons/current_location_icon.svg
  src/Pages/ProfileSetup/SetLocation/SetLocation.tsx
  src/Pages/ProfileSetup/SetLocation/SetLocationStyles.ts
  src/components/ProfileSetup/AddressSetting.tsx
  src/components/ProfileSetup/SetLocation/CurrentLocation/CurrentLocation.tsx
  src/components/ProfileSetup/SetLocation/CurrentLocation/CurrentLocationStyles.ts
  src/components/ProfileSetup/SetLocation/SetCurrentLocationBtn.tsx
  src/components/common/KakaoMap.tsx
  src/components/common/Layout/Layout.tsx
  tsconfig.json
Labels: feature

#25 위치 설정 페이지 기능 추가
  index.html
  package-lock.json
  package.json
  src/Pages/ProfileSetup/ProfileSetup.tsx
  src/Pages/ProfileSetup/ProfileSetupStyles.ts
  src/Pages/ProfileSetup/SetLocation/SetLocation.tsx
  src/components/ProfileSetup/AddressSetting.tsx
  src/components/ProfileSetup/SetLocation/CurrentLocation/CurrentLocation.tsx
  src/components/ProfileSetup/SetLocation/KakaoMap/KakaoMap.tsx
  src/components/ProfileSetup/SetLocation/KakaoMap/KakaoMapStyles.ts
  src/components/ProfileSetup/SetLocation/SetCurrentLocationBtn.tsx
  src/components/common/KakaoMap.tsx
  src/components/common/Layout/Layout.tsx
  src/components/common/Layout/LayoutStyles.ts
  src/hooks/useCurrentPosition.ts
  src/hooks/useWindowDimensions.ts
  src/main.tsx
  src/store/slices/profileAddressSlice.ts
  src/store/store.ts
  src/store/types.ts
  tsconfig.json
  vite.config.ts
Labels: Enhancement, Feature

#33 오퍼 댓글 작성 첫 페이지 화면 구현
  src/App.tsx
  src/Pages/Articles/WriteComment/GetPost/index.tsx
  src/Pages/Articles/WriteComment/WriteComment.tsx
  src/Pages/Articles/WriteComment/WriteCommentStyles.ts
  src/Pages/Articles/WriteComment/WriteOwnself/WriteOwnself.tsx
  src/Pages/Articles/WriteComment/WriteOwnself/WriteOwnselfStyles.ts
  src/components/Articles/WriteComment/InProgressbar/index.tsx
  src/components/Articles/WriteComment/Progressbar/index.tsx
  src/components/WriteComment/Progressbar/ProgressbarStyles.ts
  src/components/WriteComment/Progressbar/index.tsx
  src/components/WriteComment/WriteTypeButton/index.tsx
  src/components/common/Layout/Layout.tsx
Labels: Enhancement, Feature

#40 [오퍼 : 직접 작성하기] 댓글 달기 상세 페이지 화면 구현 완료
  .DS_Store
  .eslintrc
  package.json
  src/.DS_Store
  src/App.tsx
  src/Assets/.DS_Store
  src/Assets/Icons/.DS_Store
  src/Assets/offer/Write-comment/Close.svg
  src/Pages/Articles/Articles.tsx
  src/Pages/Articles/WriteComment/CreatePost/Progress2/Progress2.tsx
  src/Pages/Articles/WriteComment/CreatePost/Progress2/Progresss2Styles.ts
  src/Pages/Articles/WriteComment/CreatePost/Progress3/Progress3.tsx
  src/Pages/Articles/WriteComment/CreatePost/Progress3/Progresss3Styles.ts
  src/Pages/Articles/WriteComment/CreatePost/Progress4/Progress4.tsx
  src/Pages/Articles/WriteComment/CreatePost/Progress4/Progress4Styles.ts
  src/Pages/Articles/WriteComment/CreatePost/Progress5/Progress5.tsx
  src/Pages/Articles/WriteComment/CreatePost/Progress5/Progress5Styles.ts
  src/Pages/Articles/WriteComment/CreatePost/Progress6/Progress6.tsx
  src/Pages/Articles/WriteComment/CreatePost/Progress6/Progress6Styles.ts
  src/Pages/Articles/WriteComment/WriteOwnself/WriteOwnself.tsx
  src/Pages/Articles/WriteComment/WriteOwnself/WriteOwnselfStyles.ts
  src/Pages/Offer/CreateOwnOffer/CreateOwnOffer.tsx
  src/Pages/Offer/CreateOwnOffer/CreateOwnOfferStyles.ts
  src/Pages/Search/Search.tsx
  src/Pages/WriteComment/WriteComment.tsx
  src/Pages/WriteComment/WriteCommentStyles.ts
  src/components/Search/NeighborhoodSearch/NeighborhoodSearchStyles.ts
  src/components/Search/RecentSearch/RecentSearchStyles.ts
  src/components/WriteComment/CreatePost/ProcessCompo/ProcessCompo.tsx
  src/components/WriteComment/CreatePost/ProcessCompo/ProcessCompoStyles.ts
  src/components/WriteComment/Progressbar/ProgressbarStyles.ts
  src/components/WriteComment/Progressbar/index.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/Buttons/BlueButton.tsx
  src/components/common/CommonHeader/CommonHeader.tsx
  src/components/common/CommonHeader/CommonHeaderStyles.ts
  src/components/common/NavigationBar/NaviMenu.tsx
  src/components/common/NavigationBar/NaviMenu/NaviChat.tsx
  src/components/common/NavigationBar/NaviMenu/NaviHome.tsx
  src/components/common/NavigationBar/NaviMenu/NaviMy.tsx
  src/components/common/NavigationBar/NavigationBar.tsx
  src/store/slices/CreatePostSlice.ts
  src/store/store.ts
  tsconfig.json
Labels: Feature

#42 오퍼 상세 페이지 추가 화면 구현
  package-lock.json
  package.json
  src/Assets/Icons/WriteComment/Check.svg
  src/Assets/Icons/WriteComment/Link_Chain.svg
  src/Assets/Icons/WriteComment/Pencil.svg
  src/Pages/Articles/Articles.tsx
  src/Pages/Articles/ArticlesStyles.ts
  src/Pages/Articles/WriteComment/GetPost/FinalCheck/index.tsx
  src/Pages/Articles/WriteComment/GetPost/InsertPostLink/index.tsx
  src/components/Articles/LikeAndComment/index.tsx
  src/components/Articles/OfferItem/OfferItemStyles.ts
  src/components/Articles/OfferItem/index.tsx
  src/components/Articles/OfferItemLists/index.tsx
  src/components/Articles/ProductInfo/ProductInfoStyles.ts
  src/components/Articles/WriterProfile/WriterProfile.tsx
  src/components/ProfileSetup/AddressSetting.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/CommonHeader/CommonHeader.tsx
  src/components/common/CommonHeader/CommonHeaderStyles.ts
  src/components/common/RatingBadge.tsx
  src/hooks/useTimeDiff.ts
  src/styles/styled.d.ts
  src/styles/theme.ts
Labels: Feature
